// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6R6ievEO_53H_vZGsJZCr17HJnnxcCNc',
    appId: '1:1067694872382:web:ab5e51bf9d42daf6517e6f',
    messagingSenderId: '1067694872382',
    projectId: 'devoida-501b8',
    authDomain: 'devoida-501b8.firebaseapp.com',
    storageBucket: 'devoida-501b8.appspot.com',
    measurementId: 'G-6D11Q1ZG1G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhFDXM0cVrTr4j04RU08yE-Ut338YO5ok',
    appId: '1:1067694872382:android:44a3ef7975b7a75d517e6f',
    messagingSenderId: '1067694872382',
    projectId: 'devoida-501b8',
    storageBucket: 'devoida-501b8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeKsDHObcf6O_zoGFfI742zMEgU0HaREA',
    appId: '1:1067694872382:ios:72a43f56bb506462517e6f',
    messagingSenderId: '1067694872382',
    projectId: 'devoida-501b8',
    storageBucket: 'devoida-501b8.appspot.com',
    iosBundleId: 'com.example.projectManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBeKsDHObcf6O_zoGFfI742zMEgU0HaREA',
    appId: '1:1067694872382:ios:72a43f56bb506462517e6f',
    messagingSenderId: '1067694872382',
    projectId: 'devoida-501b8',
    storageBucket: 'devoida-501b8.appspot.com',
    iosBundleId: 'com.example.projectManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB6R6ievEO_53H_vZGsJZCr17HJnnxcCNc',
    appId: '1:1067694872382:web:8191d1dc732f4a69517e6f',
    messagingSenderId: '1067694872382',
    projectId: 'devoida-501b8',
    authDomain: 'devoida-501b8.firebaseapp.com',
    storageBucket: 'devoida-501b8.appspot.com',
    measurementId: 'G-6DDSKX4LXY',
  );
}
